// Shared types between frontend and backend

export enum UserRole {
  INDIVIDUAL_INVESTOR = 'INDIVIDUAL_INVESTOR',
  INSTITUTIONAL_INVESTOR = 'INSTITUTIONAL_INVESTOR',
  IMPACT_FUND = 'IMPACT_FUND',
  SME_STARTUP = 'SME_STARTUP',
  SOCIAL_ENTERPRISE = 'SOCIAL_ENTERPRISE',
  REAL_ESTATE_PROJECT = 'REAL_ESTATE_PROJECT',
  ADMIN = 'ADMIN',
}

export enum UserType {
  INVESTOR = 'INVESTOR',
  FUNDRAISER = 'FUNDRAISER',
}

export enum ProjectStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  FUNDED = 'FUNDED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum InvestmentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  ESCROWED = 'ESCROWED',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum KYCStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}


